const { MongoClient } = require('mongodb');

async function resetAllPasswords() {
    const client = new MongoClient('mongodb+srv://shreyancodes2006_db_user:NhT3AQBtQTZ4xCZa@cluster0.cymdl8r.mongodb.net/user');
    await client.connect();
    const db = client.db('pragatipulse');
    
    // Hash of "password123" (10 rounds) generated by bcrypt
    const newHash = "$2b$10$PUVgmAImf08PFzsWoEs/nuJEdBLMf4i6/SGEDvd4/8DGWBWv5lAUS";
    
    const result = await db.collection('users').updateMany(
        {},
        { $set: { passwordHash: newHash, active: true } }
    );
    
    console.log(`Reset password for ${result.modifiedCount} users to password123`);
    await client.close();
}

resetAllPasswords().catch(console.error);
